language: python
python:
  - "3.8"  
  - "3.9"
  - "3.10"

# Install dependencies
install:
  - pip install numpy

# Run tests
script:
  - python -c "import numpy as np; A = np.random.rand(5, 5); from qr_decomposition import qr_decomposition; Q, R = qr_decomposition(A); assert np.allclose(A, np.dot(Q, R)), 'QR decomposition failed'"